import type { Question } from '../types/game.js'

export const CASH_BUILDER_QUESTIONS: Question[] = [
  { id: 'cb-1', text: 'What is the capital of France?', options: ['London', 'Berlin', 'Paris', 'Madrid'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-2', text: 'Which planet is known as the Red Planet?', options: ['Venus', 'Mars', 'Jupiter', 'Saturn'], correctAnswer: 1, category: 'Science', difficulty: 'easy' },
  { id: 'cb-3', text: 'What is 7 × 8?', options: ['54', '56', '58', '60'], correctAnswer: 1, category: 'General Knowledge', difficulty: 'easy' },
  { id: 'cb-4', text: 'Who wrote Romeo and Juliet?', options: ['Charles Dickens', 'Jane Austen', 'William Shakespeare', 'Mark Twain'], correctAnswer: 2, category: 'Literature', difficulty: 'easy' },
  { id: 'cb-5', text: 'What is the chemical symbol for gold?', options: ['Go', 'Gd', 'Au', 'Ag'], correctAnswer: 2, category: 'Science', difficulty: 'easy' },
  { id: 'cb-6', text: 'In which country is the Taj Mahal?', options: ['China', 'India', 'Pakistan', 'Bangladesh'], correctAnswer: 1, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-7', text: 'How many continents are there?', options: ['5', '6', '7', '8'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-8', text: 'What is the largest mammal on Earth?', options: ['Elephant', 'Blue whale', 'Giraffe', 'Polar bear'], correctAnswer: 1, category: 'Science', difficulty: 'easy' },
  { id: 'cb-9', text: 'Which year did World War II end?', options: ['1943', '1944', '1945', '1946'], correctAnswer: 2, category: 'History', difficulty: 'easy' },
  { id: 'cb-10', text: 'What is the capital of Japan?', options: ['Seoul', 'Beijing', 'Tokyo', 'Bangkok'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-11', text: 'How many legs does a spider have?', options: ['6', '8', '10', '12'], correctAnswer: 1, category: 'Science', difficulty: 'easy' },
  { id: 'cb-12', text: 'Which country hosted the 2016 Summer Olympics?', options: ['UK', 'China', 'Brazil', 'Russia'], correctAnswer: 2, category: 'Sports', difficulty: 'easy' },
  { id: 'cb-13', text: 'What is the smallest prime number?', options: ['0', '1', '2', '3'], correctAnswer: 2, category: 'General Knowledge', difficulty: 'easy' },
  { id: 'cb-14', text: 'Who directed Jurassic Park?', options: ['James Cameron', 'Steven Spielberg', 'George Lucas', 'Christopher Nolan'], correctAnswer: 1, category: 'Movies', difficulty: 'easy' },
  { id: 'cb-15', text: 'Which planet is closest to the Sun?', options: ['Venus', 'Earth', 'Mercury', 'Mars'], correctAnswer: 2, category: 'Science', difficulty: 'easy' },
  { id: 'cb-16', text: 'What is the longest river in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], correctAnswer: 1, category: 'Geography', difficulty: 'medium' },
  { id: 'cb-17', text: 'In which city is the Eiffel Tower?', options: ['London', 'Rome', 'Paris', 'Berlin'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-18', text: 'Who sang Thriller?', options: ['Prince', 'Michael Jackson', 'Elvis', 'Stevie Wonder'], correctAnswer: 1, category: 'Music', difficulty: 'easy' },
  { id: 'cb-19', text: 'What is 12 × 12?', options: ['124', '134', '144', '154'], correctAnswer: 2, category: 'General Knowledge', difficulty: 'easy' },
  { id: 'cb-20', text: 'Which country is home to the kangaroo?', options: ['South Africa', 'New Zealand', 'Australia', 'Brazil'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-21', text: 'What gas do plants absorb from the air?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], correctAnswer: 2, category: 'Science', difficulty: 'easy' },
  { id: 'cb-22', text: 'How many strings does a standard guitar have?', options: ['4', '5', '6', '7'], correctAnswer: 2, category: 'Music', difficulty: 'easy' },
  { id: 'cb-23', text: 'Which month has 28 days?', options: ['January', 'February', 'November', 'December'], correctAnswer: 1, category: 'General Knowledge', difficulty: 'easy' },
  { id: 'cb-24', text: 'What is the capital of Italy?', options: ['Venice', 'Milan', 'Rome', 'Naples'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-25', text: 'Which animal is the tallest?', options: ['Elephant', 'Giraffe', 'Bear', 'Moose'], correctAnswer: 1, category: 'Science', difficulty: 'easy' },
  { id: 'cb-26', text: 'In what year did the Titanic sink?', options: ['1910', '1911', '1912', '1913'], correctAnswer: 2, category: 'History', difficulty: 'easy' },
  { id: 'cb-27', text: 'What is the main ingredient in guacamole?', options: ['Tomato', 'Avocado', 'Lime', 'Onion'], correctAnswer: 1, category: 'Food', difficulty: 'easy' },
  { id: 'cb-28', text: 'Which planet has the most rings?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], correctAnswer: 1, category: 'Science', difficulty: 'easy' },
  { id: 'cb-29', text: 'Who wrote Harry Potter?', options: ['J.R.R. Tolkien', 'C.S. Lewis', 'J.K. Rowling', 'Roald Dahl'], correctAnswer: 2, category: 'Literature', difficulty: 'easy' },
  { id: 'cb-30', text: 'What is the speed of light (approximately)?', options: ['300,000 km/s', '150,000 km/s', '500,000 km/s', '100,000 km/s'], correctAnswer: 0, category: 'Science', difficulty: 'medium' },
  { id: 'cb-31', text: 'Which country is sushi from?', options: ['China', 'Korea', 'Japan', 'Thailand'], correctAnswer: 2, category: 'Food', difficulty: 'easy' },
  { id: 'cb-32', text: 'How many days are in a leap year?', options: ['364', '365', '366', '367'], correctAnswer: 2, category: 'General Knowledge', difficulty: 'easy' },
  { id: 'cb-33', text: 'What is the capital of Spain?', options: ['Barcelona', 'Seville', 'Madrid', 'Valencia'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-34', text: 'Which fruit is yellow and curved?', options: ['Apple', 'Orange', 'Banana', 'Lemon'], correctAnswer: 2, category: 'Food', difficulty: 'easy' },
  { id: 'cb-35', text: 'Who painted the Mona Lisa?', options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'], correctAnswer: 1, category: 'History', difficulty: 'easy' },
  { id: 'cb-36', text: 'What is the square root of 64?', options: ['6', '7', '8', '9'], correctAnswer: 2, category: 'General Knowledge', difficulty: 'easy' },
  { id: 'cb-37', text: 'Which sport is known as the beautiful game?', options: ['Basketball', 'Football', 'Tennis', 'Cricket'], correctAnswer: 1, category: 'Sports', difficulty: 'easy' },
  { id: 'cb-38', text: 'How many states does the USA have?', options: ['48', '49', '50', '51'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-39', text: 'What does CPU stand for?', options: ['Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Core Processing Unit'], correctAnswer: 0, category: 'Technology', difficulty: 'easy' },
  { id: 'cb-40', text: 'Which band sang Bohemian Rhapsody?', options: ['The Beatles', 'Queen', 'Led Zeppelin', 'Pink Floyd'], correctAnswer: 1, category: 'Music', difficulty: 'easy' },
  { id: 'cb-41', text: 'In which ocean is the Bermuda Triangle?', options: ['Pacific', 'Indian', 'Atlantic', 'Arctic'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-42', text: 'What is H2O commonly known as?', options: ['Salt', 'Water', 'Sugar', 'Acid'], correctAnswer: 1, category: 'Science', difficulty: 'easy' },
  { id: 'cb-43', text: 'Who developed the theory of relativity?', options: ['Newton', 'Einstein', 'Galileo', 'Hawking'], correctAnswer: 1, category: 'Science', difficulty: 'easy' },
  { id: 'cb-44', text: 'Which planet is known as the Morning Star?', options: ['Mars', 'Jupiter', 'Venus', 'Mercury'], correctAnswer: 2, category: 'Science', difficulty: 'medium' },
  { id: 'cb-45', text: 'What is the largest desert in the world?', options: ['Sahara', 'Gobi', 'Antarctic', 'Arabian'], correctAnswer: 2, category: 'Geography', difficulty: 'medium' },
  { id: 'cb-46', text: 'How many players are on a football team?', options: ['9', '10', '11', '12'], correctAnswer: 2, category: 'Sports', difficulty: 'easy' },
  { id: 'cb-47', text: 'Which country invented tea?', options: ['India', 'Japan', 'China', 'UK'], correctAnswer: 2, category: 'Food', difficulty: 'easy' },
  { id: 'cb-48', text: 'What is the capital of Germany?', options: ['Munich', 'Hamburg', 'Berlin', 'Frankfurt'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-49', text: 'Which element has the symbol Fe?', options: ['Fluorine', 'Iron', 'Fermium', 'Francium'], correctAnswer: 1, category: 'Science', difficulty: 'easy' },
  { id: 'cb-50', text: 'In which year did man first land on the Moon?', options: ['1967', '1968', '1969', '1970'], correctAnswer: 2, category: 'History', difficulty: 'easy' },
  { id: 'cb-51', text: 'What is the smallest country in the world?', options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'], correctAnswer: 1, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-52', text: 'Which film won Best Picture at the 2020 Oscars?', options: ['1917', 'Parasite', 'Joker', 'Once Upon a Time'], correctAnswer: 1, category: 'Movies', difficulty: 'medium' },
  { id: 'cb-53', text: 'How many bones are in the adult human body?', options: ['186', '206', '226', '246'], correctAnswer: 1, category: 'Science', difficulty: 'easy' },
  { id: 'cb-54', text: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-55', text: 'Which sport uses a shuttlecock?', options: ['Tennis', 'Badminton', 'Squash', 'Table tennis'], correctAnswer: 1, category: 'Sports', difficulty: 'easy' },
  { id: 'cb-56', text: 'Who wrote 1984?', options: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'H.G. Wells'], correctAnswer: 1, category: 'Literature', difficulty: 'easy' },
  { id: 'cb-57', text: 'What is the boiling point of water in Celsius?', options: ['90', '100', '110', '120'], correctAnswer: 1, category: 'Science', difficulty: 'easy' },
  { id: 'cb-58', text: 'Which country is the origin of pizza?', options: ['USA', 'France', 'Italy', 'Greece'], correctAnswer: 2, category: 'Food', difficulty: 'easy' },
  { id: 'cb-59', text: 'How many Grammy Awards has Beyoncé won?', options: ['Over 20', 'Over 25', 'Over 30', 'Over 35'], correctAnswer: 2, category: 'Music', difficulty: 'medium' },
  { id: 'cb-60', text: 'What does HTML stand for?', options: ['Hyper Text Markup Language', 'High Tech Modern Language', 'Home Tool Markup Language', 'Hyperlink Text Model Language'], correctAnswer: 0, category: 'Technology', difficulty: 'easy' },
  { id: 'cb-61', text: 'Which ocean is the largest?', options: ['Atlantic', 'Indian', 'Pacific', 'Arctic'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-62', text: 'What year did the Berlin Wall fall?', options: ['1987', '1988', '1989', '1990'], correctAnswer: 2, category: 'History', difficulty: 'easy' },
  { id: 'cb-63', text: 'How many minutes in a football half?', options: ['40', '45', '50', '55'], correctAnswer: 1, category: 'Sports', difficulty: 'easy' },
  { id: 'cb-64', text: 'Which planet has the Great Red Spot?', options: ['Mars', 'Jupiter', 'Saturn', 'Neptune'], correctAnswer: 1, category: 'Science', difficulty: 'easy' },
  { id: 'cb-65', text: 'What is the capital of Canada?', options: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-66', text: 'Who directed Inception?', options: ['Nolan', 'Spielberg', 'Cameron', 'Tarantino'], correctAnswer: 0, category: 'Movies', difficulty: 'easy' },
  { id: 'cb-67', text: 'Which country produces the most coffee?', options: ['Colombia', 'Vietnam', 'Brazil', 'Ethiopia'], correctAnswer: 2, category: 'Food', difficulty: 'medium' },
  { id: 'cb-68', text: 'What is 15% of 200?', options: ['25', '30', '35', '40'], correctAnswer: 1, category: 'General Knowledge', difficulty: 'easy' },
  { id: 'cb-69', text: 'How many strings does a violin have?', options: ['2', '3', '4', '5'], correctAnswer: 2, category: 'Music', difficulty: 'easy' },
  { id: 'cb-70', text: 'Which country has the most population?', options: ['India', 'USA', 'China', 'Indonesia'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-71', text: 'What is the hardest natural substance?', options: ['Iron', 'Diamond', 'Titanium', 'Platinum'], correctAnswer: 1, category: 'Science', difficulty: 'easy' },
  { id: 'cb-72', text: 'In which year did the First World War start?', options: ['1912', '1913', '1914', '1915'], correctAnswer: 2, category: 'History', difficulty: 'easy' },
  { id: 'cb-73', text: 'What does USB stand for?', options: ['Universal Serial Bus', 'United System Buffer', 'Unified Storage Block', 'Universal Storage Byte'], correctAnswer: 0, category: 'Technology', difficulty: 'easy' },
  { id: 'cb-74', text: 'Which fruit has the most Vitamin C?', options: ['Apple', 'Orange', 'Strawberry', 'Kiwi'], correctAnswer: 3, category: 'Food', difficulty: 'medium' },
  { id: 'cb-75', text: 'How many Grand Slams has Roger Federer won?', options: ['18', '19', '20', '21'], correctAnswer: 2, category: 'Sports', difficulty: 'medium' },
  { id: 'cb-76', text: 'What is the capital of Egypt?', options: ['Alexandria', 'Cairo', 'Giza', 'Luxor'], correctAnswer: 1, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-77', text: 'Who wrote Pride and Prejudice?', options: ['Charlotte Brontë', 'Jane Austen', 'George Eliot', 'Emily Brontë'], correctAnswer: 1, category: 'Literature', difficulty: 'easy' },
  { id: 'cb-78', text: 'Which gas do humans breathe out?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], correctAnswer: 2, category: 'Science', difficulty: 'easy' },
  { id: 'cb-79', text: 'What is the tallest mountain in the world?', options: ['K2', 'Everest', 'Kilimanjaro', 'Denali'], correctAnswer: 1, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-80', text: 'Which country invented paper?', options: ['Japan', 'India', 'China', 'Egypt'], correctAnswer: 2, category: 'History', difficulty: 'easy' },
  { id: 'cb-81', text: 'How many hearts does an octopus have?', options: ['1', '2', '3', '4'], correctAnswer: 2, category: 'Science', difficulty: 'medium' },
  { id: 'cb-82', text: 'What is the capital of Russia?', options: ['St Petersburg', 'Moscow', 'Kazan', 'Sochi'], correctAnswer: 1, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-83', text: 'Which film features the quote "I\'ll be back"?', options: ['RoboCop', 'Terminator', 'Total Recall', 'Predator'], correctAnswer: 1, category: 'Movies', difficulty: 'easy' },
  { id: 'cb-84', text: 'What is the chemical symbol for silver?', options: ['Si', 'Sv', 'Ag', 'Au'], correctAnswer: 2, category: 'Science', difficulty: 'easy' },
  { id: 'cb-85', text: 'How many time zones does Russia have?', options: ['9', '10', '11', '12'], correctAnswer: 2, category: 'Geography', difficulty: 'medium' },
  { id: 'cb-86', text: 'Which country won the first football World Cup?', options: ['Brazil', 'Uruguay', 'Italy', 'Argentina'], correctAnswer: 1, category: 'Sports', difficulty: 'medium' },
  { id: 'cb-87', text: 'What is the smallest planet?', options: ['Mars', 'Mercury', 'Venus', 'Pluto'], correctAnswer: 1, category: 'Science', difficulty: 'easy' },
  { id: 'cb-88', text: 'Who painted Starry Night?', options: ['Picasso', 'Monet', 'Van Gogh', 'Rembrandt'], correctAnswer: 2, category: 'History', difficulty: 'easy' },
  { id: 'cb-89', text: 'Which continent is Iceland in?', options: ['North America', 'Europe', 'Antarctica', 'Asia'], correctAnswer: 1, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-90', text: 'What is the capital of Brazil?', options: ['Rio', 'São Paulo', 'Brasília', 'Salvador'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-91', text: 'How many sides does a hexagon have?', options: ['5', '6', '7', '8'], correctAnswer: 1, category: 'General Knowledge', difficulty: 'easy' },
  { id: 'cb-92', text: 'Which band had a hit with "Sweet Child O\' Mine"?', options: ['Aerosmith', 'Guns N\' Roses', 'Metallica', 'AC/DC'], correctAnswer: 1, category: 'Music', difficulty: 'easy' },
  { id: 'cb-93', text: 'What does RAM stand for?', options: ['Random Access Memory', 'Read Only Memory', 'Rapid Access Module', 'Real-time Application Memory'], correctAnswer: 0, category: 'Technology', difficulty: 'easy' },
  { id: 'cb-94', text: 'Which country has the most islands?', options: ['Indonesia', 'Philippines', 'Sweden', 'Norway'], correctAnswer: 2, category: 'Geography', difficulty: 'medium' },
  { id: 'cb-95', text: 'What is the largest bird?', options: ['Eagle', 'Ostrich', 'Albatross', 'Condor'], correctAnswer: 1, category: 'Science', difficulty: 'easy' },
  { id: 'cb-96', text: 'In which year was the United Nations founded?', options: ['1943', '1944', '1945', '1946'], correctAnswer: 2, category: 'History', difficulty: 'easy' },
  { id: 'cb-97', text: 'What is hummus made from?', options: ['Lentils', 'Chickpeas', 'Beans', 'Peas'], correctAnswer: 1, category: 'Food', difficulty: 'easy' },
  { id: 'cb-98', text: 'Which tennis tournament is played on clay?', options: ['Wimbledon', 'US Open', 'French Open', 'Australian Open'], correctAnswer: 2, category: 'Sports', difficulty: 'easy' },
  { id: 'cb-99', text: 'How many letters are in the English alphabet?', options: ['24', '25', '26', '27'], correctAnswer: 2, category: 'General Knowledge', difficulty: 'easy' },
  { id: 'cb-100', text: 'What is the capital of South Korea?', options: ['Busan', 'Seoul', 'Incheon', 'Daegu'], correctAnswer: 1, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-101', text: 'Which animal can hold its breath the longest?', options: ['Human', 'Elephant', 'Dolphin', 'Sperm whale'], correctAnswer: 3, category: 'Science', difficulty: 'medium' },
  { id: 'cb-102', text: 'Who directed The Godfather?', options: ['Scorsese', 'Coppola', 'Spielberg', 'Lumet'], correctAnswer: 1, category: 'Movies', difficulty: 'easy' },
  { id: 'cb-103', text: 'What is the freezing point of water in Fahrenheit?', options: ['30', '31', '32', '33'], correctAnswer: 2, category: 'Science', difficulty: 'easy' },
  { id: 'cb-104', text: 'Which country gave the Statue of Liberty to the USA?', options: ['UK', 'Spain', 'France', 'Italy'], correctAnswer: 2, category: 'History', difficulty: 'easy' },
  { id: 'cb-105', text: 'How many players in a rugby union team?', options: ['13', '14', '15', '16'], correctAnswer: 2, category: 'Sports', difficulty: 'medium' },
  { id: 'cb-106', text: 'What is the capital of India?', options: ['Mumbai', 'Kolkata', 'Delhi', 'Bangalore'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-107', text: 'Which programming language is named after coffee?', options: ['Python', 'Java', 'Ruby', 'C'], correctAnswer: 1, category: 'Technology', difficulty: 'easy' },
  { id: 'cb-108', text: 'Who wrote The Great Gatsby?', options: ['Hemingway', 'Fitzgerald', 'Steinbeck', 'Faulkner'], correctAnswer: 1, category: 'Literature', difficulty: 'easy' },
  { id: 'cb-109', text: 'What is the largest organ of the human body?', options: ['Liver', 'Brain', 'Skin', 'Heart'], correctAnswer: 2, category: 'Science', difficulty: 'easy' },
  { id: 'cb-110', text: 'Which nut is used to make marzipan?', options: ['Walnut', 'Almond', 'Hazelnut', 'Pecan'], correctAnswer: 1, category: 'Food', difficulty: 'easy' },
  { id: 'cb-111', text: 'How many points does a compass have?', options: ['4', '8', '16', '32'], correctAnswer: 3, category: 'Geography', difficulty: 'medium' },
  { id: 'cb-112', text: 'What year did Columbus reach the Americas?', options: ['1490', '1491', '1492', '1493'], correctAnswer: 2, category: 'History', difficulty: 'easy' },
  { id: 'cb-113', text: 'Which planet is named after the Roman god of war?', options: ['Jupiter', 'Saturn', 'Mars', 'Venus'], correctAnswer: 2, category: 'Science', difficulty: 'easy' },
  { id: 'cb-114', text: 'What is the capital of Argentina?', options: ['São Paulo', 'Lima', 'Buenos Aires', 'Santiago'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
  { id: 'cb-115', text: 'Who sang "Like a Virgin"?', options: ['Whitney Houston', 'Madonna', 'Janet Jackson', 'Cyndi Lauper'], correctAnswer: 1, category: 'Music', difficulty: 'easy' },
  { id: 'cb-116', text: 'How many zeros in a million?', options: ['4', '5', '6', '7'], correctAnswer: 2, category: 'General Knowledge', difficulty: 'easy' },
  { id: 'cb-117', text: 'Which vitamin is produced by sunlight?', options: ['A', 'B', 'C', 'D'], correctAnswer: 3, category: 'Science', difficulty: 'easy' },
  { id: 'cb-118', text: 'What is sushi rice seasoned with?', options: ['Soy sauce', 'Rice vinegar', 'Mirin', 'Sake'], correctAnswer: 1, category: 'Food', difficulty: 'medium' },
  { id: 'cb-119', text: 'Which country has the oldest flag?', options: ['UK', 'Denmark', 'Switzerland', 'Japan'], correctAnswer: 1, category: 'History', difficulty: 'medium' },
  { id: 'cb-120', text: 'What is the capital of China?', options: ['Shanghai', 'Hong Kong', 'Beijing', 'Shenzhen'], correctAnswer: 2, category: 'Geography', difficulty: 'easy' },
]
